import json
import os
from fastapi import APIRouter, Request

router = APIRouter()

CURRENT_API_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_API_DIR, "..", ".."))
RESOURCES_TS_PATH = os.path.join(PROJECT_ROOT, "data", "resources.ts")


@router.post("/sync")
async def sync_resources(request: Request):
    try:
        payload = await request.json()
        resources_list = payload.get("resources", [])
        json_str = json.dumps(resources_list, ensure_ascii=False, indent=2)

        ts_content = (
            "// This file can be regenerated by the local console.\n\n"
            "export type Resource = {\n"
            "  id: string;\n"
            "  name: string;\n"
            "  url: string;\n"
            "  description: string;\n"
            "  category?: string;\n"
            "  logo?: string;\n"
            "  sort?: number;\n"
            "};\n\n"
            'export const DEFAULT_RESOURCE_ICON = "/globe.svg";\n\n'
            f"export const resourcesData: Resource[] = {json_str};\n"
        )

        os.makedirs(os.path.dirname(RESOURCES_TS_PATH), exist_ok=True)
        with open(RESOURCES_TS_PATH, "w", encoding="utf-8") as f:
            f.write(ts_content)

        return {"success": True, "message": f"资源导航已更新，共 {len(resources_list)} 条。"}
    except Exception as e:
        return {"success": False, "message": f"资源同步失败: {str(e)}"}
