// This file can be regenerated by the local console.

export type Resource = {
  id: string;
  name: string;
  url: string;
  description: string;
  category?: string;
  logo?: string;
  sort?: number;
};

export const DEFAULT_RESOURCE_ICON = "/globe.svg";

export const resourcesData: Resource[] = [
  {
    id: "resource_nextjs",
    name: "Next.js",
    url: "https://nextjs.org/",
    description: "React 全栈框架，适合构建静态站点、博客与应用。",
    category: "开发工具",
    logo: "https://www.google.com/s2/favicons?domain=nextjs.org&sz=128",
    sort: 10
  },
  {
    id: "resource_tailwind",
    name: "Tailwind CSS",
    url: "https://tailwindcss.com/",
    description: "实用优先的 CSS 框架，适合快速搭建细腻的界面样式。",
    category: "设计工具",
    logo: "https://www.google.com/s2/favicons?domain=tailwindcss.com&sz=128",
    sort: 20
  },
  {
    id: "resource_github",
    name: "GitHub",
    url: "https://github.com/",
    description: "代码托管、项目协作与开源社区平台。",
    category: "开发工具",
    logo: "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    sort: 30
  }
];
